language: php

notifications:
  email:
    on_success: never
    on_failure: change

branches:
  only:
    - master

php:
  - 5.5
  - 5.6

env:
  - WP_VERSION=latest
  - WP_VERSION=4.6.1

matrix:
  include:
    - php: 5.5
      env: WP_VERSION=latest
    - php: 5.6
      env: WP_VERSION=latest
    - php: "nightly"
      env: WP_VERSION=latest


before_script:
  - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION

script: phpunit
